# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clusters',
                'doc_host': 'https://AzulushkaBravo.github.io',
                'git_url': 'https://github.com/AzulushkaBravo/clusters',
                'lib_path': 'clusters'},
  'syms': {'clusters.core': {'clusters.core.foo': ('core.html#foo', 'clusters/core.py')}}}
